### ISSUE TITLE
Notes been destoryed / replaced

### ISSUE THREAD

**Issue by td-edu** [alondmnt/joplin-plugin-history-panel#1]
I believe "History Panel" is very useful, therefore, I installed it. 

It looks nice and just as I expected, very useful for jumping around notes. 
However, I just notice that some files are either completed destroyed or partial contains of a note deleted. 

I am not sure how and when this happened. I have play around with setting after installation. Then, I noticed the above issue. (FYI: I am not sure this issue happened before or after I played with setting.)

I took some screen shots of notes along with the setting of this "History Panel".  Hope these screen shots will help to resolve the note destroy issue. 

Thanks for writing this plugin and waiting for the fix. Thanks again.
[HistoryPlugin_Issues_230430.zip](https://github.com/alondmnt/joplin-plugin-history-panel/files/11362008/HistoryPlugin_Issues_230430.zip)

**Comment by alondmnt** [comment]
Hi!

Thanks for reporting about this. Sorry to hear about it. It's the first time that I run into this issue.

Since the plugin only writes to a single note - the history log / note - in all your Joplin database ([here](https://github.com/alondmnt/joplin-plugin-history-panel/blob/main/src/history.ts#L71), [here](https://github.com/alondmnt/joplin-plugin-history-panel/blob/main/src/history.ts#L82), and [here](https://github.com/alondmnt/joplin-plugin-history-panel/blob/main/src/history.ts#L100), specifically) and never to any other note, I hope that we can trace what happened there.

## Investigation

If you go to the History Panel settings, and click on Advanced Settings you will see something similar to this:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/17462125/235955187-ddbebcf6-81fb-4a03-9597-3a6d3da86c04.png">

The history note ID should contain a single string that is the Joplin ID of that single note that the plugin writes to. You can check if the ID of that note is the same as the note that was corrupted by the plugin. You can do that directly, by comparing the string in the settings to the string that appears in the note info / properties. Or perhaps more easily, you can click the title of the panel (HISTORY), and if it opens the note that was corrupted, this means that this note is currently defined as your history note.

## Solution

If this is indeed the case, the solution is to reconfigure the history note. The recommended way to do so is to go to the note that you wish to have your logs stored in, and then select from the Tools menu `Tools-->History-->Set history note`. You only need to use this command once in order to configure the plugin, there is no need to repeat the process.

I hope this will solve your problem. I'd be happy to get your updates.

**Comment by td-edu** [comment]
The original files were overwritten already. 
but, I have tried to reproduce the issue these few days. 
Luckily, the issue was partially reproduced (only adding text to one file but not replacing a file as last time).

Attached please find screenshots of IDs. Hope these pictures  will help to pin point the issue.

![screenshot_230505-1859](https://user-images.githubusercontent.com/105232048/236594418-ff81b80b-dd4b-4b14-ab2f-f7cf613a37a0.png)
![screenshot_230505-1900](https://user-images.githubusercontent.com/105232048/236594420-431bdb45-8350-497c-9434-bd2f38833844.png)

**Comment by td-edu** [comment]
I guess I found the cause of the issue.
Please see the attached screenshot below.

Suggestion: For people just starting using this plugin, a warning msg will be nice. Or, hide this "set history note" somewhere not so easy to access since for most cases, this "history note" needed to be set once only.
![SetHistoryNote_230506_crop-w-note](https://user-images.githubusercontent.com/105232048/236648744-df213b97-b584-4537-94d7-a6541be0e226.png)

**Comment by alondmnt** [comment]
Thanks @td-edu for the detailed report.
As I suspected this was due to setting the history note.
And thanks for the suggestion, I think that you're right and that a warning may be helpful. I'll add one.
